server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: native

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-lucky-bag-1.cymexrpl0w43.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: lucky123412#$

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    safe-result-handler-enabled: false
    jdbc-type-for-null: "NULL"
    default-executor-type: reuse
    cache-enabled: true
logging:
  config: classpath:logback/logback-local.xml

